language: php
php:
  - 5.3
before_script:
  - cd ../
  - mkdir ./fs-test
  - cd fs-test
  - mkdir ./libs
  - git clone git://github.com/yiisoft/yii.git libs/yii
  - echo "yes" | php libs/yii/framework/yiic webapp . git
  - ln -s /home/travis/builds/mediasite/yii-LocalFS/ ./protected/extensions/yii-LocalFS
  - rm ./protected/tests/fixtures -R
  - rm ./protected/tests/functional -R
  - rm ./protected/tests/unit -R
  - cp ./protected/extensions/yii-LocalFS/tests/* ./protected/tests/ -R
  - mkdir ./protected/tests/log
  - sudo apt-get update
  - sudo apt-get install nginx-full php5-fpm php5 php5-cli php5-dev memcached php5-memcached gdb
  - sudo rm /etc/php5/fpm/conf.d/* -R
  - sudo cp ./protected/extensions/yii-LocalFS/travis-conf/conf.d/* /etc/php5/fpm/conf.d/
  - sudo cp ./protected/extensions/yii-LocalFS/travis-conf/php.ini /etc/php5/fpm/php.ini
  - sudo rm /etc/nginx/sites-enabled/*
  - sudo cp ./protected/extensions/yii-LocalFS/travis-conf/site.nginx /etc/nginx/sites-enabled/
  - sudo cp ./protected/extensions/yii-LocalFS/travis-conf/www.conf /etc/php5/fpm/pool.d/www.conf
  - sudo rm /home/travis/.phpenv/versions/5.3.17/etc/conf.d/* -R
  - sudo pear channel-discover pear.phpunit.de
  - sudo pear channel-discover pear.symfony.com
  - sudo pear install -a phpunit/PHPUnit
  - sudo service nginx restart
  - sleep 5
  - sudo service php5-fpm stop
  - sleep 5
  - sudo service php5-fpm start
  - sleep 5
  - cp ./protected/extensions/yii-LocalFS/travis-conf/project/* ./protected/config/
  - cd ./protected/tests
  - php --version
notifications:
  email: false
script: echo "set env MALLOC_CHECK_=3" && echo "r" | gdb --args /usr/bin/php /usr/bin/phpunit .